Optimize passing CPointer to nativecall ever so slightly
MoarVM/MoarVM pull request #1604
Opened 2021-11-16 02:01 UTC by timo

We emit an unbox_i operation in a compiled nativecall body in order to
get the pointer value to pass to the native function. Without a spesh
method on the CPointer repr, this would interpret as, and jit into, a
call to CPointer's get_int.

Instead of a call, we just emit a spesh op to do the memory offset and
read for us, which the JIT also likes very much.

2022-01-13 21:13 UTC, niner requested changes

2022-01-13 21:13 UTC, niner commented on src/6model/reprs/CPointer.c
> +        MVM_spesh_graph_add_comment(tc, g, ins, "reprop %s unsupported in P6Opaque %s",
Should probably say "in CPointer"

2025-01-25 08:07 UTC, niner approved these changes

2025-01-25 08:07 UTC, merged

2025-01-25 18:56 UTC, coke commented
This should not have been merged so close to the release.

2025-01-25 18:58 UTC, coke commented
Reverted via linked PR - please feel free to create another PR to RE-apply this, which we can do after the release today.